### PR TITLE
Improve tests for getting multiple items

### PR DESCRIPTION
**Pull request by stof**
- test that the item value is the right one when fetching items in batch
- test that the backend get is done when asking it rather than when starting the iteration (this is something which is easy to mess up when using generators, as even the code before the first ``yield`` will not run immediately).

I'm not sure whether the second test should be in ``testGetItems`` directly or in a dedicated test. Once I have your decision on it, I will write the similar test for simple-cache

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you @stoff a really good test. Im fine with it being in `testGetItems`.

**Comment by nicolas-grekas** [comment]
I'm :-1: here: PSR-6/16 have no wording about transactionality. And in fact, this breaks Symfony Cache.
Looking at the code, forcing this behavior may require a significant added complexity if not overhead.
@stof if you really think this is the required behavior, could you also please try to make it pass on Symfony Cache?

**Comment by stof** [comment]
Wel, Travis tells me it is already passing. And I knew it would for Symfony, as I forced you to put the backend fetch outside the generator function converting results to CacheItem when implementing it.

**Comment by stof** [comment]
@Nyholm you mentionned someone else btw.

**Comment by nicolas-grekas** [comment]
> put the backend fetch outside the generator

you did so for keys yes, but not for the backend fetch: they are inside the generator.
I don't know why tests pass on the CI here. I checked out your PR and it breaks locally...

**Comment by stof** [comment]
found it: all tests are actually skipped on Travis for the Symfony job. The CI setup is broken

**Comment by stof** [comment]
and the PHPCache suite has no tests in it, meaning that a green CI build is easy: nothing is running in mandatory jobs...

**Comment by Nyholm** [comment]
Oh, that is bad. I'll make sure to fix that

Does the PSR6 say anything about this?

**Comment by Nyholm** [comment]
I've updated the tests (Im using Symfony FilesystemCache now). 
I've looked at the specification and it does not provide any info about *when* the items should be fetched. But I can agree with stof that this is the expected behavior.

**Comment by nicolas-grekas** [comment]
I'm closing because I verified again on the Symfony test suite and this breaks it, and the others too (despite the Symfony job being green on Travis)

Keeping my :-1: here :)

**Pull request closed without merging**
