### PR TITLE
Test save and fetch item with no data

### PR DESCRIPTION
**Pull request by Nyholm**
Is this a valid tests? Should it this be the expected behavior?

Our adapters will fail on this.

### CODE REVIEW

**Comment by kynx** [comment]
I think that's valid. You've explicitly called `save()` and `null` is a valid value - I'd expect it to be a hit.

**Comment by cryptiklemur** [comment]
Should a save, with no value throw an exception?

**Comment by Nyholm** [comment]
> Should a save, with no value throw an exception?

No. `save()` should never throw an exception.

**Comment by cryptiklemur** [comment]
Er, return false then? If no value is set, it shouldn't be able to save, as there's nothing to save. Null isn't a default value.

**Comment by Nyholm** [comment]
I can agree with return false. It makes no sens to try to save an empty value. I'll update the PR

**Comment by jmatosp** [comment]
How can you tell that the Item has no data?

**Comment by Nyholm** [comment]
Since `null` is a valid cache value you must check `isHit`. 

``` php
if ($item->isHit() === false) {
  // This item has no data
}
```

**Comment by kynx** [comment]
@Nyholm @aequasi Sorry to come in late on this one, but it's giving me a bit of a headache... 

My understanding from the [ML](https://groups.google.com/forum/?hl=en-GB#!topic/php-fig/pxy_VYgm2sU) was that saving a deferred item turns it into a hit, whether it has a value or not. That means they'll be treated differently from non-deferred items and saved on `commit()`.

And I still think that if a user explicitly calls `save()` (or `commit()`) we should do what they ask, whether it makes sense or not.

What do you think?

**Pull request merged**
