### PR TITLE
Enhance PSR16 coverage

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. Can you make Style CI happy?

**Comment by nicolas-grekas** [comment]
done

**Comment by Nyholm** [comment]
Thank you!

**Comment by nicolas-grekas** [comment]
I'd love a new tag :)

**Comment by Nyholm** [comment]
=)

**Comment by Nyholm** [comment]
You have a new tag now. I will make another new tag after #70 is merged

**Pull request merged**
