### PR TITLE
Relax too strict requirements

### PR DESCRIPTION
**Pull request by nicolas-grekas**
I know I introduced them, but I now think this were too strict, I propose relaxing a bit the assertions.
(subtree-split canceled for this repos?)

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. We decided to have the integration tests outside of the main repo for two reasons. When someone adds a new integration test we must either: 
1) Force them to fix our build and our adapters
2) Accept a failing Travis and ruin the build process for every other PR until our issues has been fixed. 

Neither option is preferable so we will keep the integration tests in this repo. 

---

You have previously been pushing for a strict implementation (which as been appreciated btw). I'm curious **why** you changed your mind.

**Comment by nicolas-grekas** [comment]
OK thx for the explanation,
The "why" is psr-6: I don't think psr-6 is as strict as these reqs are. I don't want tests to be stricter than psr-6. Wdyt?

**Comment by cryptiklemur** [comment]
Should we add a "strict" mode for integration tests?

**Comment by nicolas-grekas** [comment]
The issue is defining what is strict and what isn't. There is only one "law", psr-6, and anything stricter than psr-6 is just not psr-6...

**Comment by cryptiklemur** [comment]
Yeah, I guess I was asking if we should have a default mode, which should just be exactly what PSR-6 is, and a `strict` mode, that would be tailored more towards extra tests that we think should be required, for cases not covered by PSR-6. But i can move that to a different ticket

**Comment by Nyholm** [comment]
I think we should follow the "law" exactly. Not be more strict than required and not be more vague then specified. The issue with PSR-6 is that a lot of things left for interpretation. 

I do not think we should have "strict PSR-6" and "normal PSR-6". 

The question is: Was the intention of PSR-6 to return false on save when saving an expired item?

``` php
    /**
     * Persists a cache item immediately.
     *
     * @param CacheItemInterface $item
     *   The cache item to save.
     *
     * @return bool
     *   True if the item was successfully persisted. False if there was an error.
     */
    public function save(CacheItemInterface $item);
```

**Comment by nicolas-grekas** [comment]
I agree with @Nyholm. My interpretation now is that since the post condition is the same (getItem/hasItem shouldn't match the expired item), the return value of save is non normative: if the item was successfully saved, then true is fine. False is also. Do you agree?

**Comment by cryptiklemur** [comment]
I wasn't saying a "Strict PSR-6", but rather a set of extra tests for the php-cache libraries

**Comment by Nyholm** [comment]
> if the item was successfully saved, then true is fine. False is also. Do you agree?

In the case with negative ttl, yes. But in the general case the return value of `save` is of importance. Example: I believe `save` should return false when you save an item with a key with length >250 with a Memcached backend. Memcached will not persist such item and our pool should tell the user that.

**Comment by kynx** [comment]
> Memcached will not persist such item and our pool should tell the user that.

@Nyholm That's my interpretation of "False if there was an error" exactly. But I'm less sure about "False if it didn't save".

FWIW I think collecting all the places where PSR-6 is a bit vague into one place (maybe a wiki on this repo?) would be a valuable thing. Ultimately it would be for FIG to issue an addendum or whatever - which may take years ;) - but in the meantime it would be a valuable resource for implementers.

**Comment by Nyholm** [comment]
I like the idea of such documentation. I've created an issue for it.

**Pull request merged**
