### PR TITLE
Loosen the composer.json requirements a bit

### PR DESCRIPTION
**Pull request by nicolas-grekas**
This would help adding this test suite to https://github.com/symfony/symfony/pull/17408

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 

I do believe that the dependency on PHPUnit should be in the `requires` since this a repository for tests. The sources (`src/`) depends on `\PHPUnit_Framework_TestCase`. 

Or am I wrong? 

Ping @samsonasik 
Related to: https://github.com/php-cache/integration-tests/pull/31/files

**Comment by nicolas-grekas** [comment]
If phpunit would ship a package with only the base test framework, I would agree, but here, this is what I get  (see below). Clearly, this is too broad.

```
  - Installing sebastian/environment (dev-master 6e71337)
    Loading from cache

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/php-token-stream (dev-master cab6c6f)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (dev-master 6150bf2)
    Loading from cache

  - Installing phpunit/php-code-coverage (dev-master 64d40a5)
    Loading from cache

  - Installing doctrine/instantiator (dev-master 8e884e7)
    Loading from cache

  - Installing sebastian/recursion-context (dev-master 913401d)
    Loading from cache

  - Installing sebastian/exporter (dev-master f88f893)
    Downloading: 100%         

  - Installing sebastian/diff (dev-master 13edfd8)
    Loading from cache

  - Installing sebastian/comparator (dev-master 937efb2)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpspec/prophecy (dev-master e55e3e3)
    Downloading: 100%         

  - Installing phpunit/phpunit-mock-objects (dev-master c4dd0c9)
    Downloading: 100%         

  - Installing sebastian/resource-operations (dev-master ce990bb)
    Loading from cache

  - Installing myclabs/deep-copy (1.5.0)
    Loading from cache

  - Installing phpunit/php-timer (dev-master 3e82f4e)
    Loading from cache

  - Installing symfony/yaml (dev-master 82287b7)
    Downloading: 100%         

  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Installing phpunit/phpunit (dev-master 5065b22)
    Downloading: 100%         

  - Removing psr/cache (dev-master 9e66031)
  - Installing psr/cache (1.0.0)
    Loading from cache

  - Installing cache/integration-tests (dev-master e001337)
    Downloading: 100%         
```

**Comment by nicolas-grekas** [comment]
Also, these base test classes are bunded inside the `phpunit`, which means you don't have to require them explicitely: if you test with phpunit, you have them already.

**Comment by Nyholm** [comment]
You are correct. Thank you.

**Pull request merged**
